-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 16:47:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pets` ;

CREATE TABLE IF NOT EXISTS `pets` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pet_name` VARCHAR(145) NULL,
  `pet_photo_name` VARCHAR(545) NULL,
  `user_ID` INT UNSIGNED NOT NULL,
  `pets_species_ID` INT UNSIGNED NOT NULL,
  `deleted` ENUM('true', 'false') NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_pets_user1_idx` (`user_ID` ASC),
  INDEX `fk_pets_pets_species1_idx` (`pets_species_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pets_species`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pets_species` ;

CREATE TABLE IF NOT EXISTS `pets_species` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pets_speciescol_name` VARCHAR(145) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(245) NULL,
  `pass` VARCHAR(245) NULL,
  `first_name` VARCHAR(145) NULL,
  `last_name` VARCHAR(145) NULL,
  `administrator` ENUM('true', 'false') NULL,
  `deleted` ENUM('true', 'false') NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `visits` ;

CREATE TABLE IF NOT EXISTS `visits` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `visit_date` DATE NULL,
  `visit_title` VARCHAR(145) NULL,
  `visit_desciption` VARCHAR(45) NULL,
  `usser_ID` INT UNSIGNED NOT NULL,
  `visit_type` ENUM('Medical Emergensy', 'Check-up', 'Cosmetc', 'Consultation') NULL,
  `visit_atachment_name` VARCHAR(545) NULL,
  `pets_ID` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  INDEX `fk_visits_usser_idx` (`usser_ID` ASC),
  INDEX `fk_visits_pets1_idx` (`pets_ID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
